name: annnet-docs-howtos
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.14
  - pip
  - pip:
      - annnet @ git+https://github.com/saezlab/annnet.git
      - graphviz
      - ipykernel>=6
      - matplotlib>=3.5
      - mkdocs>=1.6
      - mkdocs-autorefs>=1.0
      - mkdocs-jupyter>=0.25
      - mkdocs-material>=9.5
      - mkdocstrings[python]>=0.25
      - nbconvert>=7
      - networkx>=3.3
      - numcodecs>=0.12
      - openpyxl>=3.1
      - pandas>=2.0
      - polars>=0.20.0
      - pyarrow>=10
      - python-igraph>=0.11
      - zarr>=2.18
